name: egagent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - tqdm
  - pillow
  - pyarrow
  - ffmpeg
  - pytorch
  - torchvision
  - torchaudio
  - accelerate
  - datasets
  - pip:
      - aiohttp==3.12.14
      - alembic==1.16.4
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - asyncer==0.0.8
      - audioread==3.0.1
      - backoff==2.2.1
      - bitsandbytes==0.49.0
      - cachetools==6.1.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - google-ai-generativelanguage==0.9.0
      - google-auth==2.42.1
      - google-genai==1.48.0
      - graphiti-core==0.20.4
      - greenlet==3.2.3
      - httpx-sse==0.4.1
      - joblib==1.5.1
      - json-repair==0.44.1
      - jsonpatch==1.33
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-core
      - langchain-google-genai
      - langchain-experimental==0.3.4
      - langchain-openai==0.3.28
      - langchain-text-splitters==0.3.8
      - langgraph==0.5.4
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.5.2
      - langgraph-sdk==0.1.74
      - langsmith==0.4.7
      - librosa==0.11.0
      - llvmlite==0.44.0
      - magicattr==0.1.6
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - msgpack==1.1.1
      - mypy-extensions==1.1.0
      - numba==0.61.2
      - numpy==1.26.2
      - openai==1.97.0
      - optuna==4.4.0
      - ormsgpack==1.10.0
      - pooch==1.8.2
      - posthog==6.7.4
      - propcache==0.3.2
      - protobuf==3.20.3
      - pydantic==2.11.7
      - pydantic-settings==2.10.1
      - pyparsing==3.2.3
      - pypdf==6.0.0
      - pysrt==1.1.2
      - qwen-omni-utils==0.0.8
      - qwen-vl-utils==0.0.11
      - regex==2025.7.34
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - shellingham==1.5.4
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.41
      - tenacity==9.1.2
      - tokenizers==0.21.2
      - transformers==4.53.2
      - typer==0.17.4
      - types-pyyaml==6.0.12.20250822
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - ujson==5.10.0
      - wandb==0.21.0
      - yarl==1.20.1
      - zstandard==0.23.0