name: egagent
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.8.1=pyhe01879c_0
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiosignal=1.4.0=py310h06a4308_0
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - arrow=1.3.0=pyhd8ed1ab_1
  - arrow-cpp=19.0.0=hfcf91c8_3
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - chardet=4.0.0=py310hff52083_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cryptography=45.0.7=py310h0a354b3_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - datasets=3.6.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=2.26.0=py310h06a4308_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-generativeai=0.8.5=pyh29332c3_0
  - googleapis-common-protos=1.69.2=py310h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.71.0=py310h6a678d5_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.31.4=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - krb5=1.21.3=h8a1dbc1_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurl=8.14.1=h31d0fb7_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lightning-utilities=0.14.3=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.0.2=py310h5764c6d_1
  - multiprocess=0.70.12.2=py310h5764c6d_2
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.11.0=py310hf4471f9_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.1.1=hd396ef6_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310h6a678d5_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - peft=0.16.0=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310hb1c3d2d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - proto-plus=1.26.1=py310h06a4308_0
  - psutil=5.9.1=py310h5764c6d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=19.0.0=py310h6a678d5_1
  - pyasn1=0.6.1=py310h06a4308_0
  - pyasn1-modules=0.4.2=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic-core=2.33.2=py310hc6f7160_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyopenssl=25.3.0=py310hef88997_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py310h5764c6d_1
  - python_abi=3.10=2_cp310
  - pytorch=2.2.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=py310h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py310h922eef2_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py310h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h993c535_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.2.1=py310_cu121
  - torchmetrics=1.7.4=pyhd8ed1ab_0
  - torchtriton=2.2.0=py310
  - torchvision=0.17.1=py310_cu121
  - tornado=6.5.1=py310h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250708=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f98852_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohttp==3.12.14
      - alembic==1.16.4
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - asyncer==0.0.8
      - audioread==3.0.1
      - backoff==2.2.1
      - bitsandbytes==0.46.1
      - cachetools==6.1.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - dspy==2.6.27
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - google-ai-generativelanguage==0.9.0
      - google-auth==2.42.1
      - google-genai==1.48.0
      - graphiti-core==0.20.4
      - greenlet==3.2.3
      - httpx-sse==0.4.1
      - joblib==1.5.1
      - json-repair==0.44.1
      - jsonpatch==1.33
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-core==0.3.69
      - langchain-experimental==0.3.4
      - langchain-neo4j==0.5.0
      - langchain-openai==0.3.28
      - langchain-text-splitters==0.3.8
      - langgraph==0.5.4
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.5.2
      - langgraph-sdk==0.1.74
      - langsmith==0.4.7
      - librosa==0.11.0
      - llvmlite==0.44.0
      - magicattr==0.1.6
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - msgpack==1.1.1
      - mypy-extensions==1.1.0
      - neo4j==5.28.2
      - neo4j-graphrag==1.10.0
      - numba==0.61.2
      - numpy==1.26.0
      - openai==1.97.0
      - optuna==4.4.0
      - ormsgpack==1.10.0
      - pooch==1.8.2
      - posthog==6.7.4
      - propcache==0.3.2
      - protobuf==3.20.3
      - pydantic==2.11.7
      - pydantic-settings==2.10.1
      - pyparsing==3.2.3
      - pypdf==6.0.0
      - pysrt==1.1.2
      - qwen-omni-utils==0.0.8
      - qwen-vl-utils==0.0.11
      - regex==2025.7.34
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - shellingham==1.5.4
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.41
      - tenacity==9.1.2
      - thinc==8.3.6
      - tokenizers==0.21.2
      - transformers==4.53.2
      - typer==0.17.4
      - types-pyyaml==6.0.12.20250822
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - ujson==5.10.0
      - wandb==0.21.0
      - yarl==1.20.1
      - zstandard==0.23.0
